/**
 * Database constants for malts, hops, yeasts, BJCP styles, water profiles, salt ions, mash presets, equipment profiles, and preset recipes.
 * Focused on practical, high-quality homebrewing equipment and ingredients widely used by homebrewers.
 */

export const MALTS = [
  // Basmalter
  {
    name: 'Weyermann Pilsner Malt',
    ebc: 3.5,
    yield: 80,
    type: 'base',
    desc: 'Klassisk tysk basmalt för ren, krispig pilsner, helles och ljus lager.',
  },
  {
    name: 'Viking Pilsner Malt',
    ebc: 4,
    yield: 80,
    type: 'base',
    desc: 'Prisvärd och krispig nordisk pilsnermalt. Utmärkt för lager och ales.',
  },
  {
    name: 'Viking Pale Ale Malt',
    ebc: 6,
    yield: 79,
    type: 'base',
    desc: 'Maltig, fyllig basmalt. Perfekt ryggrad för IPA, APA och hantverks-ales.',
  },
  {
    name: 'Crisp Maris Otter',
    ebc: 6,
    yield: 78,
    type: 'base',
    desc: 'Brittisk golvmaltad basmalt med underbar nötsmak och fyllig brödighet.',
  },
  {
    name: 'Simpson Golden Promise',
    ebc: 6,
    yield: 77,
    type: 'base',
    desc: 'Skotsk basmalt med mjuk, ren och lätt söt maltsmak. Populär i IPA & Pale Ale.',
  },
  {
    name: 'Weyermann Wienermalt / Vienna',
    ebc: 8,
    yield: 78,
    type: 'base',
    desc: 'Gyllene färg och nötsmak. Bra i Märzen, Wiener, Amber och Pale Ales.',
  },
  {
    name: 'Weyermann Münchenmalt I',
    ebc: 15,
    yield: 77,
    type: 'base',
    desc: 'Fyllig brödighet och Maillard-toner. Bra i mörka lagers, bock och mörka ales.',
  },
  {
    name: 'Weyermann Münchenmalt II',
    ebc: 25,
    yield: 76,
    type: 'base',
    desc: 'Mörkare Münchenmalt med djup maltsötma och maltig arom.',
  },
  {
    name: 'Vetemalt (Ljus)',
    ebc: 4,
    yield: 79,
    type: 'base',
    desc: 'Ger fin skumkrona, fyllighet och dis i Hefeweizen, Witbier och NEIPA.',
  },
  {
    name: 'Vetemalt (Mörk)',
    ebc: 10,
    yield: 77,
    type: 'base',
    desc: 'Mörkare vetemalt för Dunkelweizen och fylliga mörka ales.',
  },
  {
    name: 'Rågmalt / Rye Malt',
    ebc: 6,
    yield: 74,
    type: 'base',
    desc: 'Fyllig, kryddig rågkaraktär för råg-IPA, saison och gårdsöl.',
  },
  {
    name: 'Havregrynsmalt / Oat Malt',
    ebc: 5,
    yield: 72,
    type: 'base',
    desc: 'Maltad havre. Ger en silkeslen munkänsla och mjuk fyllighet i Oatmeal Stout & NEIPA.',
  },
  {
    name: 'Viking Smoked Malt (Rökmalt)',
    ebc: 6,
    yield: 77,
    type: 'base',
    desc: 'Bokrökt basmalt. Subtil rökton. Essentiell i Rauchbier, Gotlandsdricka och rökporter.',
  },

  // Ekologiska & Kultursorter
  {
    name: 'Warbro Kvarn Ölandsvete',
    ebc: 5,
    yield: 75,
    type: 'base',
    desc: 'Ekologisk svensk kultursort från Warbro Kvarn. Rustik, nötaktig vetekaraktär.',
  },
  {
    name: 'Warbro Kvarn Svedjeråg',
    ebc: 7,
    yield: 72,
    type: 'base',
    desc: 'Ekologisk svensk kultursort från Warbro Kvarn. Fyllig, kryddig rågton.',
  },
  {
    name: 'Dinkelmalt (Spelt)',
    ebc: 6,
    yield: 75,
    type: 'base',
    desc: 'Ekologisk dinkelmalt. Fyllig, nötaktig smak med utmärkt skumstabilitet.',
  },

  // Karamelmalter
  {
    name: 'CaraPils / Carafoam (Weyermann)',
    ebc: 4,
    yield: 73,
    type: 'cara',
    desc: 'Ger skumstabilitet och fyllighet utan sötma eller färgändring.',
  },
  {
    name: 'Caramalt / Crystal 20',
    ebc: 40,
    yield: 71,
    type: 'cara',
    desc: 'Lätt kola och mild sötma. Bra i engelska ales och pale ales.',
  },
  {
    name: 'Crystal 60 / Cara 60',
    ebc: 120,
    yield: 70,
    type: 'cara',
    desc: 'Söt karamell och toffee. Klassisk pale ale- och amber ale-ingrediens.',
  },
  {
    name: 'Crystal 120 / Cara 150',
    ebc: 295,
    yield: 68,
    type: 'cara',
    desc: 'Mörk karamell, russin och torkad frukt. Används sparsamt.',
  },
  {
    name: 'Caramünchen I (Weyermann)',
    ebc: 50,
    yield: 70,
    type: 'cara',
    desc: 'Tysk karamelmalt med balanserad brödighet och karamellsötma.',
  },
  {
    name: 'Caramünchen III (Weyermann)',
    ebc: 150,
    yield: 67,
    type: 'cara',
    desc: 'Mörk karamellmalt med toner av torkad frukt, russin och mörk kola.',
  },
  {
    name: 'Caravienne (Castle Malting)',
    ebc: 40,
    yield: 71,
    type: 'cara',
    desc: 'Belgisk karamelmalt med mild sötma och kolatoner.',
  },
  {
    name: 'Viking Cookie Malt',
    ebc: 50,
    yield: 73,
    type: 'cara',
    desc: 'Ger smak av mörka kex, bageri och rostat bröd utan bitterhet.',
  },
  {
    name: 'Château Biscuit (Castle Malting)',
    ebc: 50,
    yield: 72,
    type: 'cara',
    desc: 'Belgisk kexmalt. Ger en doft av rostat bröd och nybakade kex.',
  },
  {
    name: 'Château Special B (Castle Malting)',
    ebc: 300,
    yield: 68,
    type: 'cara',
    desc: 'Intensiv mörk belgisk karamelmalt. Mörk frukt, russin, plommon.',
  },
  {
    name: 'Weyermann Melanoidinmalt',
    ebc: 70,
    yield: 73,
    type: 'cara',
    desc: 'Ger rik Maillard-brödighet och djup röd-brun färg. Bra i bock & märzen.',
  },

  // Rostade malter
  {
    name: 'Brown Malt',
    ebc: 150,
    yield: 70,
    type: 'roasted',
    desc: 'Klassisk brittisk porter-malt. Nöt, rostbröd och mjuk kaffe.',
  },
  {
    name: 'Viking Chocolate Light',
    ebc: 450,
    yield: 65,
    type: 'roasted',
    desc: 'Mjuk choklad- och kaffeton utan strävhet. Utmärkt i porter och stout.',
  },
  {
    name: 'Chokladmalt / Chocolate Malt',
    ebc: 900,
    yield: 65,
    type: 'roasted',
    desc: 'Intensiv mörk choklad och rostat kaffe. Stout och porter.',
  },
  {
    name: 'Carafa Special I (Avhästad)',
    ebc: 600,
    yield: 67,
    type: 'roasted',
    desc: 'Mjukare, avhästat chokladmalt. Ger djup färg utan strävhet.',
  },
  {
    name: 'Carafa Special III (Avhästad)',
    ebc: 1200,
    yield: 62,
    type: 'roasted',
    desc: 'Djup svart färg med mjuk smak. Perfekt för Schwarzbier och mörk IPA.',
  },
  {
    name: 'Svartmalt / Black Patent',
    ebc: 1400,
    yield: 60,
    type: 'roasted',
    desc: 'Extrem rostning. Används sparsamt för färg och sträva toner.',
  },
  {
    name: 'Rostat korn (Roasted Barley)',
    ebc: 1300,
    yield: 60,
    type: 'roasted',
    desc: 'Omaltat rostat korn. Ger torr kaffesmak och vitt skum. Klassiker i Dry Stout.',
  },

  // Adjunkter & Flingor
  {
    name: 'Havreflingor (Flaked Oats)',
    ebc: 3,
    yield: 65,
    type: 'adjunct',
    desc: 'Omaltad havre. Ger silkig textur och dimighet i NEIPA och Oatmeal Stout.',
  },
  {
    name: 'Veteflingor (Flaked Wheat)',
    ebc: 3,
    yield: 68,
    type: 'adjunct',
    desc: 'Protein och disighet för Witbier och Hazy IPA.',
  },
  {
    name: 'Kornflingor (Flaked Barley)',
    ebc: 3,
    yield: 65,
    type: 'adjunct',
    desc: 'Ger fyllighet och fin skumkrona i Stouts och Bitters.',
  },
  {
    name: 'Majsflingor (Flaked Corn)',
    ebc: 2,
    yield: 65,
    type: 'adjunct',
    desc: 'Neutral sötma för Cream Ale och amerikansk lager.',
  },

  // Socker, Extrakt & Tillsatser
  {
    name: 'Sackaros (Strösocker)',
    ebc: 0,
    yield: 100,
    type: 'sugar',
    desc: 'Rent socker. Ökar alkoholhalten utan att ge kropp.',
  },
  {
    name: 'Laktos (Mjölksocker)',
    ebc: 0,
    yield: 70,
    type: 'sugar',
    desc: 'Icke-jäsbart socker. Ger fyllig sötma och krämig munkänsla i Milkshake IPA & Stout.',
  },
  {
    name: 'Kandissocker (Ljust)',
    ebc: 5,
    yield: 96,
    type: 'sugar',
    desc: 'Belgisk kandis. Ökar alkoholhalten och torkar ut slutsmaken i Tripel & Saison.',
  },
  {
    name: 'Kandissocker (Mörkt)',
    ebc: 400,
    yield: 96,
    type: 'sugar',
    desc: 'Mörk belgisk kandis. Ger fylliga toner av russin, plommon och sirap.',
  },
  {
    name: 'Honung',
    ebc: 3,
    yield: 75,
    type: 'sugar',
    desc: 'Ger subtil honungsarom. Tillsätts bäst mot slutet av koket eller i fermentorn.',
  },
  {
    name: 'Maltextrakt (DME, Ljust)',
    ebc: 6,
    yield: 97,
    type: 'sugar',
    desc: 'Torrt maltextrakt för snabb-bryggning och jäststarter.',
  },
  {
    name: 'Maltextrakt (LME, Ljust)',
    ebc: 6,
    yield: 80,
    type: 'sugar',
    desc: 'Flytande maltextrakt för enkelt bryggande.',
  },
];

export const HOPS = [
  // Aromahumle & IPA-favoriter
  {
    name: 'Citra',
    alpha_min: 11.0,
    alpha_max: 13.5,
    use: 'aroma',
    origin: 'US',
    desc: 'Intensiv tropisk frukt, mango, lime och persika. Kungen av IPA & NEIPA.',
  },
  {
    name: 'Mosaic',
    alpha_min: 11.5,
    alpha_max: 13.5,
    use: 'aroma',
    origin: 'US',
    desc: 'Komplex tropisk frukt, blåbär, citrus och örter. Extremt populär allrounder.',
  },
  {
    name: 'Simcoe',
    alpha_min: 12.0,
    alpha_max: 14.5,
    use: 'aroma',
    origin: 'US',
    desc: 'Passionsfrukt, tall, kåda och citrus. Favorit i West Coast IPA & NEIPA.',
  },
  {
    name: 'Cascade',
    alpha_min: 4.5,
    alpha_max: 7.0,
    use: 'dual',
    origin: 'US',
    desc: 'Grapefrukt, citrus och blommig arom. Den klassiska APA-humlen.',
  },
  {
    name: 'Centennial',
    alpha_min: 9.0,
    alpha_max: 12.0,
    use: 'dual',
    origin: 'US',
    desc: 'Citrus och blomster. "Super Cascade" för Pale Ale & IPA.',
  },
  {
    name: 'Amarillo',
    alpha_min: 8.0,
    alpha_max: 11.0,
    use: 'dual',
    origin: 'US',
    desc: 'Apelsin, persika och blommig sötma. Fruktig och mångsidig.',
  },
  {
    name: 'Chinook',
    alpha_min: 12.0,
    alpha_max: 14.0,
    use: 'dual',
    origin: 'US',
    desc: 'Barrträd, tall, jordnära och kraftfull ren beska.',
  },
  {
    name: 'Columbus / CTZ',
    alpha_min: 14.0,
    alpha_max: 16.5,
    use: 'dual',
    origin: 'US',
    desc: 'Kraftig beska, kryddig och örtig pepprighet.',
  },
  {
    name: 'Galaxy',
    alpha_min: 13.0,
    alpha_max: 15.5,
    use: 'aroma',
    origin: 'AU',
    desc: 'Passionsfrukt, citrus och persika. Australisk stjärnhumle.',
  },
  {
    name: 'Nelson Sauvin',
    alpha_min: 12.0,
    alpha_max: 14.0,
    use: 'aroma',
    origin: 'NZ',
    desc: 'Krusbär, vitvinstoner (Sauvignon Blanc) och grapefrukt.',
  },
  {
    name: 'Nectaron',
    alpha_min: 12.0,
    alpha_max: 14.5,
    use: 'aroma',
    origin: 'NZ',
    desc: 'Persika, nektarin, ananas och tropik. Eftertraktad nyazeeländare.',
  },
  {
    name: 'Superdelic',
    alpha_min: 9.0,
    alpha_max: 12.0,
    use: 'aroma',
    origin: 'NZ',
    desc: 'Röd frukt, mango, godis och fräsch citrus.',
  },
  {
    name: 'Sabro',
    alpha_min: 12.0,
    alpha_max: 15.0,
    use: 'aroma',
    origin: 'US',
    desc: 'Kokos, tropisk frukt, ceder och mynta. Unik smakprofil.',
  },
  {
    name: 'Talus',
    alpha_min: 8.0,
    alpha_max: 11.0,
    use: 'aroma',
    origin: 'US',
    desc: 'Pink grapefruit, torkade rosor, tall och tropisk frukt.',
  },
  {
    name: 'Idaho 7',
    alpha_min: 13.0,
    alpha_max: 15.0,
    use: 'aroma',
    origin: 'US',
    desc: 'Guava, apelsin, svart te och tall.',
  },
  {
    name: 'El Dorado',
    alpha_min: 13.0,
    alpha_max: 15.0,
    use: 'aroma',
    origin: 'US',
    desc: 'Vattenmelon, päron, godis och tropisk frukt.',
  },

  // Europeiska Ädel- & Lagerhumle
  {
    name: 'Saaz',
    alpha_min: 2.5,
    alpha_max: 4.5,
    use: 'aroma',
    origin: 'CZ',
    desc: 'Klassisk tjeckisk ädelhumle. Mild, kryddig och örtig pilsnerhumle.',
  },
  {
    name: 'Hallertau Mittelfrüh',
    alpha_min: 3.0,
    alpha_max: 5.5,
    use: 'aroma',
    origin: 'DE',
    desc: 'Fin blomster- och kryddarom. Klassisk tyska lagerhumle.',
  },
  {
    name: 'Tettnanger',
    alpha_min: 3.0,
    alpha_max: 5.5,
    use: 'aroma',
    origin: 'DE',
    desc: 'Mild, kryddig med lätt blomsterarom.',
  },
  {
    name: 'Spalter Select',
    alpha_min: 4.0,
    alpha_max: 6.0,
    use: 'aroma',
    origin: 'DE',
    desc: 'Delikat och ren örtig arom för lager och pilsner.',
  },
  {
    name: 'Perle',
    alpha_min: 6.0,
    alpha_max: 9.0,
    use: 'dual',
    origin: 'DE',
    desc: 'Fin kryddig arom och mjuk ren beska.',
  },
  {
    name: 'Magnum',
    alpha_min: 11.0,
    alpha_max: 14.5,
    use: 'bittering',
    origin: 'DE',
    desc: 'Ren neutral beskehumle. Låter aromahumlen tala fritt.',
  },
  {
    name: 'Hallertau Blanc',
    alpha_min: 9.0,
    alpha_max: 12.0,
    use: 'aroma',
    origin: 'DE',
    desc: 'Passionsfrukt, vindruvor, citrus. Modern tysk aroma.',
  },

  // Brittiska Humlesorter
  {
    name: 'Fuggles',
    alpha_min: 3.5,
    alpha_max: 6.0,
    use: 'dual',
    origin: 'UK',
    desc: 'Jordnära, örtlig, träig. Klassisk engelsk porter/bitter.',
  },
  {
    name: 'East Kent Goldings',
    alpha_min: 4.0,
    alpha_max: 6.5,
    use: 'aroma',
    origin: 'UK',
    desc: 'Silkeslen honungskrydda. Den brittiska klassikern för ales & stouts.',
  },

  // Svensk Kulturarvshumle
  {
    name: 'Svensk Korsta (SWE 25)',
    alpha_min: 7.0,
    alpha_max: 9.5,
    use: 'dual',
    origin: 'SE',
    desc: 'Svensk kulturarvshumle från Sundsvall (1769). Tropisk frukt, grapefrukt och friskt gräs.',
  },
  {
    name: 'Svensk Svalöf Mauritz 85',
    alpha_min: 3.0,
    alpha_max: 5.5,
    use: 'aroma',
    origin: 'SE',
    desc: 'Svensk förädlingshumle från Svalöv. Örtig, blommig och mild citrus.',
  },
];

export const YEASTS = [
  // Torr- & Ale-jäst
  {
    name: 'SafAle US-05',
    lab: 'Fermentis',
    type: 'ale',
    att_min: 73,
    att_max: 78,
    temp_min: 15,
    temp_max: 22,
    desc: 'Hembryggarens mest använda ale-jäst. Ren, neutral profil för APA, IPA, Stout.',
  },
  {
    name: 'SafAle S-04',
    lab: 'Fermentis',
    type: 'ale',
    att_min: 71,
    att_max: 75,
    temp_min: 18,
    temp_max: 22,
    desc: 'Brittisk alejäst. Snabb flockning, fyllig kropp och mild fruktighet.',
  },
  {
    name: 'Lallemand Verdant IPA',
    lab: 'Lallemand',
    type: 'ale',
    att_min: 72,
    att_max: 77,
    temp_min: 19,
    temp_max: 23,
    desc: 'Tropisk frukt och mjuk len kropp. Förstahandsval för NEIPA & Hazy IPA.',
  },
  {
    name: 'Wyeast 1318 London Ale III',
    lab: 'Wyeast',
    type: 'ale',
    att_min: 71,
    att_max: 75,
    temp_min: 18,
    temp_max: 23,
    desc: 'Brödig och fruktig flytande jäststorsäljare för NEIPA.',
  },
  {
    name: 'Nottingham Ale',
    lab: 'Lallemand',
    type: 'ale',
    att_min: 73,
    att_max: 82,
    temp_min: 14,
    temp_max: 21,
    desc: 'Hög förgäsning, neutral och extremt robust. Klarar breda temperaturer.',
  },
  {
    name: 'Lallemand BRY-97 West Coast',
    lab: 'Lallemand',
    type: 'ale',
    att_min: 75,
    att_max: 80,
    temp_min: 15,
    temp_max: 22,
    desc: 'Amerikansk West Coast-jäst. Hög flockning och mycket ren krispig smak.',
  },

  // Kveik (Jäs varmt i rumstemperatur utan kylning!)
  {
    name: 'Lallemand Voss Kveik',
    lab: 'Lallemand',
    type: 'ale',
    att_min: 75,
    att_max: 82,
    temp_min: 25,
    temp_max: 40,
    desc: 'Norsk kveik. Extremt snabb jäsning vid 35–40°C med fräsch apelsinarom utan finkeloljor!',
  },
  {
    name: 'Omega Lutra Kveik',
    lab: 'Omega Yeast',
    type: 'ale',
    att_min: 75,
    att_max: 82,
    temp_min: 20,
    temp_max: 35,
    desc: 'Extremt ren neutral kveik. Blixtsnabb jäsning för "fejk-lager" eller ren ale vid rumstemp.',
  },
  {
    name: 'Omega Hornindal Kveik',
    lab: 'Omega Yeast',
    type: 'ale',
    att_min: 75,
    att_max: 82,
    temp_min: 22,
    temp_max: 37,
    desc: 'Tropisk mango/ananas-kveik för Hazy IPAs och fruktdrivna ales.',
  },

  // Lager- & Hybridjäst
  {
    name: 'SafLager W-34/70',
    lab: 'Fermentis',
    type: 'lager',
    att_min: 71,
    att_max: 75,
    temp_min: 9,
    temp_max: 15,
    desc: 'Världens mest använda lagerjäst. Ren, krispig och stabil Weihenstephan-stam.',
  },
  {
    name: 'Lallemand Novalager',
    lab: 'Lallemand',
    type: 'lager',
    att_min: 78,
    att_max: 84,
    temp_min: 12,
    temp_max: 20,
    desc: 'Modern hybridlagerjäst. Krispig lagerprofil som kan jäsa varmare (15–18°C) utan diacetyl!',
  },
  {
    name: 'SafLager S-23',
    lab: 'Fermentis',
    type: 'lager',
    att_min: 70,
    att_max: 75,
    temp_min: 9,
    temp_max: 15,
    desc: 'Sydtysk lagerjäst med lätt fruktiga undertoner.',
  },

  // Sura Öl & Belgisk Jäst
  {
    name: 'Lallemand Philly Sour',
    lab: 'Lallemand',
    type: 'wild',
    att_min: 72,
    att_max: 77,
    temp_min: 20,
    temp_max: 25,
    desc: 'Unik jäststams-art som bildar mjölksyra direkt under första dagarnas jäsning för Sour IPA & Berliner Weisse.',
  },
  {
    name: 'SafAle BE-134 Saison',
    lab: 'Fermentis',
    type: 'belgian',
    att_min: 80,
    att_max: 90,
    temp_min: 18,
    temp_max: 28,
    desc: 'Saisonjäst i torrform med hög förgäsning och pepprig avslutning.',
  },
  {
    name: 'Wyeast 3068 Weizen',
    lab: 'Wyeast',
    type: 'wheat',
    att_min: 73,
    att_max: 77,
    temp_min: 18,
    temp_max: 24,
    desc: 'Klassisk tysk Hefeweizen. Perfekt balans mellan banan och kryddnejlika.',
  },
  {
    name: 'Safbrew WB-06',
    lab: 'Fermentis',
    type: 'wheat',
    att_min: 76,
    att_max: 80,
    temp_min: 18,
    temp_max: 24,
    desc: 'Torr vete-jäst för kryddig tysk Hefeweizen.',
  },
];

export const STYLES = [
  // Bohemska & tyska lagers
  {
    id: '3A',
    category: 'Lager – Ljus',
    name: 'Bohemsk Pilsner',
    og_min: 1.044,
    og_max: 1.06,
    fg_min: 1.013,
    fg_max: 1.017,
    ibu_min: 30,
    ibu_max: 45,
    ebc_min: 7,
    ebc_max: 12,
    abv_min: 4.2,
    abv_max: 5.4,
  },
  {
    id: '5D',
    category: 'Lager – Ljus',
    name: 'Tysk Pilsner',
    og_min: 1.044,
    og_max: 1.05,
    fg_min: 1.008,
    fg_max: 1.013,
    ibu_min: 22,
    ibu_max: 40,
    ebc_min: 4,
    ebc_max: 10,
    abv_min: 4.4,
    abv_max: 5.2,
  },
  {
    id: '4A',
    category: 'Lager – Ljus',
    name: 'München Helles',
    og_min: 1.044,
    og_max: 1.048,
    fg_min: 1.006,
    fg_max: 1.012,
    ibu_min: 16,
    ibu_max: 22,
    ebc_min: 6,
    ebc_max: 10,
    abv_min: 4.7,
    abv_max: 5.4,
  },
  {
    id: '6A',
    category: 'Lager – Amber',
    name: 'Märzen / Oktoberfest',
    og_min: 1.054,
    og_max: 1.06,
    fg_min: 1.01,
    fg_max: 1.014,
    ibu_min: 18,
    ibu_max: 24,
    ebc_min: 16,
    ebc_max: 33,
    abv_min: 4.8,
    abv_max: 5.9,
  },
  {
    id: '6C',
    category: 'Lager – Mörk',
    name: 'Helles Bock / Maibock',
    og_min: 1.064,
    og_max: 1.072,
    fg_min: 1.011,
    fg_max: 1.018,
    ibu_min: 23,
    ibu_max: 35,
    ebc_min: 10,
    ebc_max: 20,
    abv_min: 6.3,
    abv_max: 7.4,
  },
  {
    id: '6B',
    category: 'Lager – Mörk',
    name: 'Traditionell Bock',
    og_min: 1.064,
    og_max: 1.072,
    fg_min: 1.013,
    fg_max: 1.019,
    ibu_min: 20,
    ibu_max: 27,
    ebc_min: 39,
    ebc_max: 59,
    abv_min: 6.3,
    abv_max: 7.2,
  },
  {
    id: '8A',
    category: 'Lager – Mörk',
    name: 'München Dunkel',
    og_min: 1.048,
    og_max: 1.056,
    fg_min: 1.01,
    fg_max: 1.016,
    ibu_min: 18,
    ibu_max: 28,
    ebc_min: 28,
    ebc_max: 55,
    abv_min: 4.5,
    abv_max: 5.6,
  },
  {
    id: '8B',
    category: 'Lager – Mörk',
    name: 'Schwarzbier',
    og_min: 1.046,
    og_max: 1.052,
    fg_min: 1.01,
    fg_max: 1.016,
    ibu_min: 20,
    ibu_max: 30,
    ebc_min: 37,
    ebc_max: 59,
    abv_min: 4.4,
    abv_max: 5.4,
  },
  {
    id: '9C',
    category: 'Lager – Mörk',
    name: 'Baltic Porter',
    og_min: 1.06,
    og_max: 1.09,
    fg_min: 1.016,
    fg_max: 1.024,
    ibu_min: 20,
    ibu_max: 40,
    ebc_min: 33,
    ebc_max: 79,
    abv_min: 6.5,
    abv_max: 9.5,
  },

  // Brittiska ales
  {
    id: '11A',
    category: 'Ale – Brittisk',
    name: 'Ordinary Bitter',
    og_min: 1.03,
    og_max: 1.039,
    fg_min: 1.007,
    fg_max: 1.011,
    ibu_min: 25,
    ibu_max: 35,
    ebc_min: 16,
    ebc_max: 28,
    abv_min: 3.2,
    abv_max: 3.8,
  },
  {
    id: '11B',
    category: 'Ale – Brittisk',
    name: 'Best Bitter',
    og_min: 1.04,
    og_max: 1.048,
    fg_min: 1.008,
    fg_max: 1.012,
    ibu_min: 25,
    ibu_max: 40,
    ebc_min: 16,
    ebc_max: 31,
    abv_min: 3.8,
    abv_max: 4.6,
  },
  {
    id: '11C',
    category: 'Ale – Brittisk',
    name: 'Strong Bitter / ESB',
    og_min: 1.048,
    og_max: 1.06,
    fg_min: 1.01,
    fg_max: 1.016,
    ibu_min: 30,
    ibu_max: 50,
    ebc_min: 16,
    ebc_max: 35,
    abv_min: 4.6,
    abv_max: 6.2,
  },
  {
    id: '14A',
    category: 'Ale – Brittisk',
    name: 'Scottish Heavy 70/-',
    og_min: 1.035,
    og_max: 1.04,
    fg_min: 1.01,
    fg_max: 1.015,
    ibu_min: 10,
    ibu_max: 20,
    ebc_min: 26,
    ebc_max: 43,
    abv_min: 3.2,
    abv_max: 3.9,
  },
  {
    id: '13C',
    category: 'Ale – Brittisk',
    name: 'English Porter',
    og_min: 1.04,
    og_max: 1.052,
    fg_min: 1.008,
    fg_max: 1.014,
    ibu_min: 18,
    ibu_max: 35,
    ebc_min: 39,
    ebc_max: 59,
    abv_min: 4.0,
    abv_max: 5.4,
  },
  {
    id: '17C',
    category: 'Ale – Brittisk',
    name: 'Old Ale',
    og_min: 1.055,
    og_max: 1.088,
    fg_min: 1.015,
    fg_max: 1.022,
    ibu_min: 30,
    ibu_max: 60,
    ebc_min: 22,
    ebc_max: 79,
    abv_min: 5.5,
    abv_max: 9.0,
  },
  {
    id: '17E',
    category: 'Ale – Brittisk',
    name: 'English Barleywine',
    og_min: 1.08,
    og_max: 1.12,
    fg_min: 1.018,
    fg_max: 1.03,
    ibu_min: 35,
    ibu_max: 70,
    ebc_min: 16,
    ebc_max: 43,
    abv_min: 8.0,
    abv_max: 12.0,
  },

  // Stout
  {
    id: '15A',
    category: 'Ale – Stout',
    name: 'Dry Irish Stout',
    og_min: 1.036,
    og_max: 1.044,
    fg_min: 1.007,
    fg_max: 1.011,
    ibu_min: 25,
    ibu_max: 40,
    ebc_min: 49,
    ebc_max: 79,
    abv_min: 4.0,
    abv_max: 4.5,
  },
  {
    id: '15B',
    category: 'Ale – Stout',
    name: 'Oatmeal Stout',
    og_min: 1.045,
    og_max: 1.065,
    fg_min: 1.01,
    fg_max: 1.018,
    ibu_min: 25,
    ibu_max: 40,
    ebc_min: 43,
    ebc_max: 79,
    abv_min: 4.2,
    abv_max: 5.9,
  },
  {
    id: '16D',
    category: 'Ale – Stout',
    name: 'Foreign Extra Stout',
    og_min: 1.056,
    og_max: 1.075,
    fg_min: 1.01,
    fg_max: 1.018,
    ibu_min: 30,
    ibu_max: 70,
    ebc_min: 59,
    ebc_max: 99,
    abv_min: 6.3,
    abv_max: 8.0,
  },
  {
    id: '20A',
    category: 'Ale – Stout',
    name: 'Russian Imperial Stout',
    og_min: 1.075,
    og_max: 1.115,
    fg_min: 1.018,
    fg_max: 1.03,
    ibu_min: 50,
    ibu_max: 90,
    ebc_min: 59,
    ebc_max: 99,
    abv_min: 8.0,
    abv_max: 12.0,
  },

  // Amerikanska ales
  {
    id: '18B',
    category: 'Ale – Amerikansk',
    name: 'American Pale Ale',
    og_min: 1.045,
    og_max: 1.06,
    fg_min: 1.01,
    fg_max: 1.015,
    ibu_min: 30,
    ibu_max: 50,
    ebc_min: 6,
    ebc_max: 14,
    abv_min: 4.5,
    abv_max: 6.2,
  },
  {
    id: '21A',
    category: 'Ale – Hoppy',
    name: 'American IPA',
    og_min: 1.056,
    og_max: 1.07,
    fg_min: 1.008,
    fg_max: 1.014,
    ibu_min: 40,
    ibu_max: 70,
    ebc_min: 12,
    ebc_max: 28,
    abv_min: 5.5,
    abv_max: 7.5,
  },
  {
    id: '21C',
    category: 'Ale – Hoppy',
    name: 'Hazy / NEIPA',
    og_min: 1.06,
    og_max: 1.085,
    fg_min: 1.01,
    fg_max: 1.015,
    ibu_min: 25,
    ibu_max: 60,
    ebc_min: 6,
    ebc_max: 14,
    abv_min: 6.0,
    abv_max: 9.0,
  },
  {
    id: '22A',
    category: 'Ale – Hoppy',
    name: 'Double IPA',
    og_min: 1.065,
    og_max: 1.1,
    fg_min: 1.008,
    fg_max: 1.018,
    ibu_min: 60,
    ibu_max: 120,
    ebc_min: 12,
    ebc_max: 28,
    abv_min: 7.5,
    abv_max: 10.0,
  },

  // Belgiska ales
  {
    id: '24A',
    category: 'Ale – Belgisk',
    name: 'Witbier',
    og_min: 1.044,
    og_max: 1.052,
    fg_min: 1.008,
    fg_max: 1.012,
    ibu_min: 8,
    ibu_max: 20,
    ebc_min: 4,
    ebc_max: 8,
    abv_min: 4.5,
    abv_max: 5.5,
  },
  {
    id: '25B',
    category: 'Ale – Belgisk',
    name: 'Saison',
    og_min: 1.048,
    og_max: 1.065,
    fg_min: 1.002,
    fg_max: 1.012,
    ibu_min: 20,
    ibu_max: 35,
    ebc_min: 10,
    ebc_max: 28,
    abv_min: 3.5,
    abv_max: 9.0,
  },
  {
    id: '26B',
    category: 'Ale – Belgisk',
    name: 'Belgian Dubbel',
    og_min: 1.062,
    og_max: 1.075,
    fg_min: 1.008,
    fg_max: 1.018,
    ibu_min: 15,
    ibu_max: 25,
    ebc_min: 20,
    ebc_max: 33,
    abv_min: 6.0,
    abv_max: 7.6,
  },
  {
    id: '26C',
    category: 'Ale – Belgisk',
    name: 'Belgian Tripel',
    og_min: 1.075,
    og_max: 1.085,
    fg_min: 1.008,
    fg_max: 1.014,
    ibu_min: 20,
    ibu_max: 40,
    ebc_min: 9,
    ebc_max: 14,
    abv_min: 7.5,
    abv_max: 9.5,
  },
  {
    id: '27A',
    category: 'Ale – Belgisk',
    name: 'Belgian Strong Dark',
    og_min: 1.075,
    og_max: 1.11,
    fg_min: 1.01,
    fg_max: 1.024,
    ibu_min: 20,
    ibu_max: 35,
    ebc_min: 24,
    ebc_max: 43,
    abv_min: 8.0,
    abv_max: 12.0,
  },

  // Veteöl
  {
    id: '10A',
    category: 'Ale – Vete',
    name: 'Hefeweizen',
    og_min: 1.044,
    og_max: 1.052,
    fg_min: 1.01,
    fg_max: 1.014,
    ibu_min: 8,
    ibu_max: 15,
    ebc_min: 6,
    ebc_max: 18,
    abv_min: 4.3,
    abv_max: 5.6,
  },
  {
    id: '10B',
    category: 'Ale – Vete',
    name: 'Dunkelweizen',
    og_min: 1.044,
    og_max: 1.056,
    fg_min: 1.01,
    fg_max: 1.014,
    ibu_min: 10,
    ibu_max: 18,
    ebc_min: 28,
    ebc_max: 45,
    abv_min: 4.3,
    abv_max: 5.6,
  },
  {
    id: '10C',
    category: 'Ale – Vete',
    name: 'Weizenbock',
    og_min: 1.064,
    og_max: 1.09,
    fg_min: 1.015,
    fg_max: 1.022,
    ibu_min: 15,
    ibu_max: 30,
    ebc_min: 14,
    ebc_max: 59,
    abv_min: 6.5,
    abv_max: 9.0,
  },
];

export const WATER_PROFILES = [
  { name: 'Stockholm (Mälaren - Lovö/Norsborg)', ca: 17, mg: 3, na: 14, cl: 20, so4: 20, hco3: 65 },
  { name: 'Göteborg (Göta Älv / Alelyckan)', ca: 10, mg: 2, na: 10, cl: 15, so4: 10, hco3: 40 },
  { name: 'Malmö / Lund (Sydvatten - Vomb)', ca: 32, mg: 7, na: 18, cl: 30, so4: 30, hco3: 120 },
  { name: 'Uppsala (Kalkrikt grundvatten)', ca: 75, mg: 12, na: 25, cl: 40, so4: 45, hco3: 240 },
  { name: 'Norrland / Kiruna (Fjällvatten)', ca: 5, mg: 1, na: 2, cl: 3, so4: 5, hco3: 15 },
  { name: 'Gotland / Visby (Kalksten/Hårt)', ca: 90, mg: 15, na: 35, cl: 60, so4: 50, hco3: 280 },
  { name: 'Örebro (Svartån/Vättern)', ca: 22, mg: 4, na: 12, cl: 18, so4: 22, hco3: 80 },
  { name: 'Pilsen (Tjeckien)', ca: 7, mg: 3, na: 2, cl: 5, so4: 5, hco3: 25 },
  { name: 'München (Bayern)', ca: 75, mg: 18, na: 2, cl: 2, so4: 5, hco3: 295 },
  { name: 'Burton-on-Trent (England)', ca: 352, mg: 24, na: 44, cl: 16, so4: 820, hco3: 320 },
  { name: 'Destillerat / RO-vatten', ca: 0, mg: 0, na: 0, cl: 0, so4: 0, hco3: 0 },
];

export const SALT_IONS = {
  gypsum: { ca: 232.8, mg: 0, na: 0, cl: 0, so4: 557.9, hco3: 0 }, // CaSO4·2H2O
  calciumChloride: { ca: 272.6, mg: 0, na: 0, cl: 483.4, so4: 0, hco3: 0 }, // CaCl2·2H2O
  epsomSalt: { ca: 0, mg: 98.6, na: 0, cl: 0, so4: 389.7, hco3: 0 }, // MgSO4·7H2O
  tableSalt: { ca: 0, mg: 0, na: 393.5, cl: 606.5, so4: 0, hco3: 0 }, // NaCl
  chalk: { ca: 400.5, mg: 0, na: 0, cl: 0, so4: 0, hco3: 1200 }, // CaCO3
  bakingSoda: { ca: 0, mg: 0, na: 273.4, cl: 0, so4: 0, hco3: 724.0 }, // NaHCO3
};

export const MASH_PRESETS = {
  single_infusion: {
    name: 'Enkelt infusion',
    steps: [
      { name: 'Sackarifikation', type: 'Infusion', temp: 67, time: 60 },
      { name: 'Avmäskning', type: 'Infusion', temp: 78, time: 10 },
    ],
  },
  step_mash: {
    name: 'Stegmäskning',
    steps: [
      { name: 'Beta-amylasrast', type: 'Steg', temp: 63, time: 30 },
      { name: 'Sackarifikation', type: 'Steg', temp: 72, time: 30 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
  },
  full_step: {
    name: 'Full stegmäskning (med proteinrast)',
    steps: [
      { name: 'Inläggning', type: 'Infusion', temp: 52, time: 15 },
      { name: 'Beta-amylasrast', type: 'Steg', temp: 63, time: 30 },
      { name: 'Alfa-amylasrast', type: 'Steg', temp: 72, time: 20 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
  },
  decoction: {
    name: 'Dekoktion (enkel)',
    steps: [
      { name: 'Inläggning', type: 'Infusion', temp: 55, time: 20 },
      { name: 'Sackarifikation', type: 'Dekoktion', temp: 68, time: 40 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
  },
};

export const EQUIPMENT_PROFILES = [
  {
    id: 'grainfather_g30',
    name: 'Grainfather G30 v2 (23L)',
    batchVolume: 23,
    efficiency: 75,
    boilOffRate: 2.8,
    kettleLoss: 2.0,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'grainfather_g40',
    name: 'Grainfather G40 (38L)',
    batchVolume: 38,
    efficiency: 77,
    boilOffRate: 3.2,
    kettleLoss: 3.0,
    fermenterLoss: 1.5,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'brewtools_b40',
    name: 'Brewtools B40pro (30L)',
    batchVolume: 30,
    efficiency: 78,
    boilOffRate: 3.5,
    kettleLoss: 2.5,
    fermenterLoss: 1.5,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'brewtools_b80',
    name: 'Brewtools B80pro (50L)',
    batchVolume: 50,
    efficiency: 80,
    boilOffRate: 4.5,
    kettleLoss: 3.5,
    fermenterLoss: 2.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'brewzilla_35l',
    name: 'BrewZilla / Robobrew 35L Gen 4 (20L)',
    batchVolume: 20,
    efficiency: 72,
    boilOffRate: 3.0,
    kettleLoss: 2.0,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'brewzilla_65l',
    name: 'BrewZilla 65L Gen 4 (45L)',
    batchVolume: 45,
    efficiency: 75,
    boilOffRate: 4.0,
    kettleLoss: 3.0,
    fermenterLoss: 1.5,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'brewmonk_30l',
    name: 'Brew Monk 30L (20L)',
    batchVolume: 20,
    efficiency: 73,
    boilOffRate: 3.0,
    kettleLoss: 2.0,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'coobra_30l',
    name: 'Coobra Craft Brewer 30 v5 (20L)',
    batchVolume: 20,
    efficiency: 72,
    boilOffRate: 3.0,
    kettleLoss: 2.0,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'brewster_beacon_40',
    name: 'Brewster Beacon 40L (25L)',
    batchVolume: 25,
    efficiency: 74,
    boilOffRate: 3.2,
    kettleLoss: 2.2,
    fermenterLoss: 1.2,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'speidel_20l',
    name: 'Speidel Braumeister 20L',
    batchVolume: 20,
    efficiency: 78,
    boilOffRate: 2.5,
    kettleLoss: 1.8,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'klarstein_30l',
    name: 'Klarstein Mundschenk 30L (20L)',
    batchVolume: 20,
    efficiency: 72,
    boilOffRate: 3.0,
    kettleLoss: 2.0,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'igloo_cooler_36l',
    name: 'Kylväska / Tre-kärls-system (36L Igloo + Gryta)',
    batchVolume: 20,
    efficiency: 76,
    boilOffRate: 3.0,
    kettleLoss: 1.5,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
  {
    id: 'biab_20l',
    name: 'BIAB / Påsbryggning (30L Spisgryta)',
    batchVolume: 20,
    efficiency: 70,
    boilOffRate: 3.2,
    kettleLoss: 1.5,
    fermenterLoss: 1.0,
    grainAbsorption: 0.8,
    mashRatio: 4.5,
  },
  {
    id: 'koksbryggeriet_4l',
    name: 'Lilla Köksbryggeriet 4L (Spisbryggning)',
    batchVolume: 4,
    efficiency: 68,
    boilOffRate: 1.0,
    kettleLoss: 0.5,
    fermenterLoss: 0.3,
    grainAbsorption: 1.0,
    mashRatio: 3.5,
  },
  {
    id: 'custom_30l',
    name: 'Standard Gryta 30L',
    batchVolume: 20,
    efficiency: 75,
    boilOffRate: 3.0,
    kettleLoss: 2.0,
    fermenterLoss: 1.0,
    grainAbsorption: 0.96,
    mashRatio: 3.0,
  },
];

export const PRESET_RECIPES = [
  {
    id: 'hazy_neipa',
    name: 'Juicy Hazy NEIPA (Tropical Hop Bomb)',
    styleId: '21C',
    description: 'Saftig, fyllig och kraftfullt aromhumlad Hazy IPA med Citra, Mosaic, Simcoe och havremalt.',
    recipe: {
      name: 'Juicy Hazy NEIPA',
      styleId: '21C',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Ladda med whirlpool- och torrhumle. Använd Lallemand Verdant, Wyeast 1318 eller Voss Kveik.',
    },
    fermentables: [
      { name: 'Viking Pale Ale Malt', amount: 3.8, ebc: 6, yield: 79, type: 'base' },
      { name: 'Vetemalt (Ljus)', amount: 0.8, ebc: 4, yield: 79, type: 'base' },
      { name: 'Havremalt / Oat Malt', amount: 0.6, ebc: 5, yield: 72, type: 'base' },
      { name: 'Havreflingor (Flaked Oats)', amount: 0.4, ebc: 3, yield: 65, type: 'adjunct' },
    ],
    hops: [
      { name: 'Magnum', amount: 10, alpha: 12.0, time: 60, form: 'pellets', use: 'kok' },
      { name: 'Citra', amount: 30, alpha: 12.0, time: 0, form: 'pellets', use: 'whirlpool' },
      { name: 'Mosaic', amount: 30, alpha: 12.5, time: 0, form: 'pellets', use: 'whirlpool' },
      { name: 'Citra', amount: 50, alpha: 12.0, time: 0, form: 'pellets', use: 'torrhumle' },
      { name: 'Mosaic', amount: 50, alpha: 12.5, time: 0, form: 'pellets', use: 'torrhumle' },
    ],
    yeast: {
      name: 'Lallemand Verdant IPA',
      lab: 'Lallemand',
      type: 'ale',
      attMin: 72,
      attMax: 77,
      tempMin: 19,
      tempMax: 23,
      notes: 'Ger silkeslen munkänsla och tropiska estrar.',
    },
    mash: [
      { name: 'Sackarifikation', type: 'Infusion', temp: 67, time: 60 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 17, mg: 3, na: 14, cl: 120, so4: 60, hco3: 65 },
      salts: { gypsum: 1, calciumChloride: 4, epsomSalt: 0, tableSalt: 1, chalk: 0, bakingSoda: 0 },
    },
  },
  {
    id: 'west_coast_ipa',
    name: 'West Coast IPA (Krispig & Tallbarrs-Citrus)',
    styleId: '21A',
    description: 'Klassisk krispig och ren West Coast IPA med spetsig beska, kåda, grapefrukt och tall.',
    recipe: {
      name: 'West Coast IPA',
      styleId: '21A',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Krispig profil. Bryggs på Pale Ale malt, Simcoe, Citra och Centennial.',
    },
    fermentables: [
      { name: 'Viking Pale Ale Malt', amount: 5.0, ebc: 6, yield: 79, type: 'base' },
      { name: 'Weyermann Wienermalt / Vienna', amount: 0.5, ebc: 8, yield: 78, type: 'base' },
      { name: 'CaraPils / Carafoam (Weyermann)', amount: 0.2, ebc: 4, yield: 73, type: 'cara' },
    ],
    hops: [
      { name: 'Columbus / CTZ', amount: 20, alpha: 15.0, time: 60, form: 'pellets', use: 'kok' },
      { name: 'Centennial', amount: 25, alpha: 10.0, time: 15, form: 'pellets', use: 'kok' },
      { name: 'Simcoe', amount: 30, alpha: 13.0, time: 5, form: 'pellets', use: 'kok' },
      { name: 'Citra', amount: 40, alpha: 12.0, time: 0, form: 'pellets', use: 'torrhumle' },
      { name: 'Simcoe', amount: 40, alpha: 13.0, time: 0, form: 'pellets', use: 'torrhumle' },
    ],
    yeast: {
      name: 'SafAle US-05',
      lab: 'Fermentis',
      type: 'ale',
      attMin: 73,
      attMax: 78,
      tempMin: 18,
      tempMax: 21,
      notes: 'Jäs svalt för ren profil utan estrar.',
    },
    mash: [
      { name: 'Sackarifikation', type: 'Infusion', temp: 65, time: 60 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 50, mg: 10, na: 20, cl: 50, so4: 150, hco3: 50 },
      salts: { gypsum: 5, calciumChloride: 1, epsomSalt: 1, tableSalt: 0, chalk: 0, bakingSoda: 0 },
    },
  },
  {
    id: 'klassisk_pilsner',
    name: 'Klassisk Lager / Pilsner (Krispig & Mjuk)',
    styleId: '5D',
    description: 'Ren, krispig och balanserad hantverkspilsner med 100% Pilsnermalt, Saaz och mjuk beska.',
    recipe: {
      name: 'Klassisk Lager / Pilsner',
      styleId: '5D',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Klassisk pilsner med Saflager W-34/70 eller Novalager.',
    },
    fermentables: [
      { name: 'Weyermann Pilsner Malt', amount: 4.4, ebc: 3.5, yield: 80, type: 'base' },
      { name: 'CaraPils / Carafoam (Weyermann)', amount: 0.2, ebc: 4, yield: 73, type: 'cara' },
    ],
    hops: [
      { name: 'Perle', amount: 20, alpha: 7.0, time: 60, form: 'pellets', use: 'kok' },
      { name: 'Saaz', amount: 30, alpha: 3.5, time: 15, form: 'pellets', use: 'kok' },
      { name: 'Saaz', amount: 20, alpha: 3.5, time: 5, form: 'pellets', use: 'kok' },
    ],
    yeast: {
      name: 'SafLager W-34/70',
      lab: 'Fermentis',
      type: 'lager',
      attMin: 71,
      attMax: 75,
      tempMin: 9,
      tempMax: 13,
      notes: 'Jäs svalt vid 10–12°C. Kan även jäsa med Novalager vid 15°C.',
    },
    mash: [
      { name: 'Sackarifikation', type: 'Infusion', temp: 66, time: 60 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 17, mg: 3, na: 14, cl: 20, so4: 20, hco3: 65 },
      salts: { gypsum: 1, calciumChloride: 1, epsomSalt: 0, tableSalt: 0, chalk: 0, bakingSoda: 0 },
    },
  },
  {
    id: 'choklad_porter',
    name: 'Fyllig Choklad & Kaffe Porter',
    styleId: '13C',
    description: 'Mörk, fyllig porter med rika toner av mörk choklad, kaffe och knäckig karamellsötma.',
    recipe: {
      name: 'Fyllig Choklad & Kaffe Porter',
      styleId: '13C',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Fyllig portersmak med Carafa Special, Brown malt och mjuk chokladmalt.',
    },
    fermentables: [
      { name: 'Crisp Maris Otter', amount: 3.8, ebc: 6, yield: 78, type: 'base' },
      { name: 'Caramünchen I (Weyermann)', amount: 0.4, ebc: 50, yield: 70, type: 'cara' },
      { name: 'Brown Malt', amount: 0.3, ebc: 150, yield: 70, type: 'roasted' },
      { name: 'Viking Chocolate Light', amount: 0.25, ebc: 450, yield: 65, type: 'roasted' },
      { name: 'Carafa Special I (Avhästad)', amount: 0.15, ebc: 600, yield: 67, type: 'roasted' },
    ],
    hops: [
      { name: 'East Kent Goldings', amount: 35, alpha: 5.0, time: 60, form: 'pellets', use: 'kok' },
      { name: 'Fuggles', amount: 20, alpha: 4.5, time: 15, form: 'pellets', use: 'kok' },
    ],
    yeast: {
      name: 'SafAle S-04',
      lab: 'Fermentis',
      type: 'ale',
      attMin: 71,
      attMax: 75,
      tempMin: 18,
      tempMax: 21,
      notes: 'Ger mjuk fyllighet och låter maltkaraktären skinna.',
    },
    mash: [
      { name: 'Sackarifikation', type: 'Infusion', temp: 67, time: 60 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 32, mg: 7, na: 18, cl: 30, so4: 30, hco3: 120 },
      salts: { gypsum: 1, calciumChloride: 2, epsomSalt: 0, tableSalt: 0, chalk: 1, bakingSoda: 1 },
    },
  },
  {
    id: 'hefeweizen',
    name: 'Bayersk Hefeweizen (Banan & Kryddnejlika)',
    styleId: '10A',
    description: 'Klassiskt tyskt veteöl med aromer av banan, kryddnejlika och en disig silkeslen kropp.',
    recipe: {
      name: 'Bayersk Hefeweizen',
      styleId: '10A',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Fruktigt veteöl med skumkrona.',
    },
    fermentables: [
      { name: 'Vetemalt (Ljus)', amount: 2.6, ebc: 4, yield: 79, type: 'base' },
      { name: 'Weyermann Pilsner Malt', amount: 1.8, ebc: 3.5, yield: 80, type: 'base' },
      { name: 'Weyermann Münchenmalt I', amount: 0.3, ebc: 15, yield: 77, type: 'base' },
    ],
    hops: [
      { name: 'Hallertau Mittelfrüh', amount: 25, alpha: 4.0, time: 60, form: 'pellets', use: 'kok' },
    ],
    yeast: {
      name: 'Wyeast 3068 Weizen',
      lab: 'Wyeast',
      type: 'wheat',
      attMin: 73,
      attMax: 77,
      tempMin: 18,
      tempMax: 22,
      notes: 'Jäs runt 20°C för bra balans mellan banan och kryddnejlika.',
    },
    mash: [
      { name: 'Proteinrast', type: 'Steg', temp: 52, time: 15 },
      { name: 'Sackarifikation', type: 'Steg', temp: 67, time: 45 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 40, mg: 8, na: 15, cl: 40, so4: 40, hco3: 80 },
      salts: { gypsum: 1, calciumChloride: 1, epsomSalt: 0, tableSalt: 0, chalk: 0, bakingSoda: 0 },
    },
  },
  {
    id: 'sommar_session_ale',
    name: 'Sommar Session Pale Ale (4.5% Lättdrucken)',
    styleId: '18B',
    description: 'Uppfriskande och lättdrucken 4.5% sommar-ale laddad med fräsch Cascade- & Citra-humle.',
    recipe: {
      name: 'Sommar Session Pale Ale',
      styleId: '18B',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Perfekt 4.5% session ale med krispig kropp och citrusaktig humlearom.',
    },
    fermentables: [
      { name: 'Viking Pale Ale Malt', amount: 3.0, ebc: 6, yield: 79, type: 'base' },
      { name: 'Viking Cookie Malt', amount: 0.2, ebc: 50, yield: 73, type: 'cara' },
      { name: 'CaraPils / Carafoam (Weyermann)', amount: 0.15, ebc: 4, yield: 73, type: 'cara' },
    ],
    hops: [
      { name: 'Magnum', amount: 12, alpha: 12.0, time: 60, form: 'pellets', use: 'kok' },
      { name: 'Cascade', amount: 20, alpha: 5.5, time: 15, form: 'pellets', use: 'kok' },
      { name: 'Citra', amount: 25, alpha: 12.0, time: 5, form: 'pellets', use: 'kok' },
    ],
    yeast: {
      name: 'SafAle US-05',
      lab: 'Fermentis',
      type: 'ale',
      attMin: 73,
      attMax: 77,
      tempMin: 18,
      tempMax: 21,
      notes: 'Ren och krispig avslutning.',
    },
    mash: [
      { name: 'Sackarifikation', type: 'Infusion', temp: 66, time: 60 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 17, mg: 3, na: 14, cl: 20, so4: 50, hco3: 65 },
      salts: { gypsum: 2, calciumChloride: 1, epsomSalt: 0, tableSalt: 0, chalk: 0, bakingSoda: 0 },
    },
  },
  {
    id: 'gotlandsdricka',
    name: 'Gotlandsdricka / Svensk Gårdsöl',
    styleId: '25B',
    description: 'Traditionell nordisk brygd med bokrökt malt, svedjeråg och snabb Kveik-jäsning.',
    recipe: {
      name: 'Gotlandsdricka / Svensk Gårdsöl',
      styleId: '25B',
      batchVolume: 20,
      boilVolume: 25,
      boilTime: 60,
      efficiency: 75,
      notes: 'Traditionell brygd. Tillsätt gärna färskt enbärsris i mäsken.',
    },
    fermentables: [
      { name: 'Viking Smoked Malt (Rökmalt)', amount: 2.2, ebc: 6, yield: 77, type: 'base' },
      { name: 'Viking Pilsner Malt', amount: 1.8, ebc: 4, yield: 80, type: 'base' },
      { name: 'Warbro Kvarn Svedjeråg', amount: 0.5, ebc: 7, yield: 72, type: 'base' },
      { name: 'Honung', amount: 0.25, ebc: 3, yield: 75, type: 'sugar' },
    ],
    hops: [
      { name: 'Svensk Korsta (SWE 25)', amount: 25, alpha: 8.0, time: 60, form: 'pellets', use: 'kok' },
      { name: 'Saaz', amount: 20, alpha: 3.5, time: 15, form: 'pellets', use: 'kok' },
    ],
    yeast: {
      name: 'Lallemand Voss Kveik',
      lab: 'Lallemand',
      type: 'ale',
      attMin: 75,
      attMax: 82,
      tempMin: 28,
      tempMax: 38,
      notes: 'Jäs varmt i rumstemperatur (28–35°C) för snabb och fruktig avslutning.',
    },
    mash: [
      { name: 'Råg & Rök-rast', type: 'Steg', temp: 64, time: 45 },
      { name: 'Sackarifikation', type: 'Steg', temp: 70, time: 20 },
      { name: 'Avmäskning', type: 'Steg', temp: 78, time: 10 },
    ],
    water: {
      volume: 25,
      base: { ca: 90, mg: 15, na: 35, cl: 60, so4: 50, hco3: 280 },
      salts: { gypsum: 1, calciumChloride: 1, epsomSalt: 0, tableSalt: 0, chalk: 0, bakingSoda: 0 },
    },
  },
];
